# 配置文件
# 单位: 像素
# 这里使用的是PHash

# 比较的文件
base: screenshot/0all.jpg

# 模板目录文件
pathPart: img/number

# 模板扩展名
partExt: jpg

# 图片滑动step
stepX: 2
stepY: 2

# 比较文件单位格子宽高(不写则和模板图片宽高一致)
baseW: 75
baseH: 100

# PHash相似度要求
similarLimit: 8

# 取精确值时模糊的像素宽度(会在匹配点周围搜索,找到最匹配的一个点)(最小值为'图片滑动step'的最大值)
blurryPixel: 5
